<?php $formats = $this->driver->getFormats(); ?>
<p class="format-list">
<?php foreach ($formats as $format): ?>
  <?php if ($translated = $this->transEsc($format)): ?>
    <span class="format <?=$this->record($this->driver)->getFormatClass($format) ?>"><?=$translated ?></span>
  <?php endif; ?>
<?php endforeach; ?>
</p>
<?php if (!in_array(\CRL\Module::ONLINE_FORMAT, $formats)): ?>
<p>Note that CRL will <a href="https://www.crl.edu/services/digital-services/digital-delivery" target="_blank">digitize material</a> from the collection when copyright allows.</p>
<?php endif; ?>

