<?php
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    $doi = $this->doi($this->driver, 'holdings');
    $doiActive = $doi->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    $total_items = 0;
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = [
          'holdings' => [],
          'electronic_holdings' => [],
          'total' => 0,
          'page' => 0,
          'itemLimit' => 0
        ];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<?php if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
    <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<?php endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>

<?php if (!$this->driver->isOnline()): ?>
  <a href="<?=$this->url('content-page', ['page' => 'borrowing']) ?>" class="toolbar-btn" data-lightbox=""><?=$this->transEsc('Borrow this resource')?></a>
<?php endif; ?>

<?php if (!empty($urls) || $openUrlActive || $doiActive): ?>
  <h3><?=$this->transEsc("Internet")?></h3>
  <?php if (!empty($urls)): ?>
    <?php foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <?php endforeach; ?>
  <?php endif; ?>
  <?php if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><?php endif; ?>
  <?php if ($doiActive): ?><?=$doi->renderTemplate()?><?php endif; ?>
<?php endif; ?>

<?php if (!empty($holdings['electronic_holdings'])): ?>
  <?=
    $this->context($this)->renderInContext(
        'RecordTab/holdingsils/electronic.phtml',
        ['holdings' => $holdings['electronic_holdings']]
    );
  ?>
<?php endif; ?>

<?php if (!empty($holdings['holdings'])): ?>
  <?php foreach ($holdings['holdings'] ?? [] as $holding): ?>


    <?php if (!empty($holding['textfields'])): ?>
      <?php foreach ($holding['textfields'] ?? [] as $textFieldName => $textFields): ?>
        <h3><?=$textFieldName == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textFieldName))?></h3>
        <?php foreach ($textFields as $current): ?>
              <?=$this->linkify($this->escapeHtml($current))?><br/>
        <?php endforeach; ?>
      <?php endforeach; ?>
    <?php endif; ?>


    <?php if (!empty($holding['items'])): ?>
      <?php $total_items++; ?>
      <h3><?=$this->transEsc("Item List")?></h3>
      <table class="table table-striped">
      <th><?=$this->transEsc("Description")?></th>
      <th><?=$this->transEsc("Local Call Number")?></th>
      <th><?=$this->transEsc("Status")?></th>
      <?php
      // Sort items by volume for a more friendly display
      $keys = array_column($holding['items'], 'volume');
      array_multisort($keys, SORT_ASC, SORT_NATURAL, $holding['items']);
      ?>
      <?php foreach ($holding['items'] as $row): ?>
      <tr vocab="http://schema.org/" typeof="Offer">
        <td><?=$this->escapeHtml($row['volume'])?>
        <?php if (isset($row['item_notes'])): ?>
          <div class="item-notes">
            <?=$this->transEsc("Item Notes")?>:<br/>
            <ul>
              <?php foreach ($row['item_notes'] as $item_note): ?>
                <li><?=$this->escapeHtml($item_note) ?></li>
              <?php endforeach; ?>
            </ul>
          </div>
        <?php endif; ?></td>
        <td><?=$this->escapeHtml($row['callnumber'])?></td>
        <td>
          <?php if ($row['reserve'] == "Y"): ?>
            <link property="availability" href="http://schema.org/InStoreOnly" />
            <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
          <?php endif; ?>
          <?php if ($row['use_unknown_message'] ?? false): ?>
            <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
          <?php else: ?>
            <?php if ($row['availability'] ?? false): ?>
              <?php /* Begin Available Items (Holds) */ ?>
               <span class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>
              <?php if ($row['link'] ?? false): ?>
                <a class="<?=$check ? 'checkRequest ' : ''?>placehold" <?php if (!empty($row['linkLightbox'])): ?>data-lightbox <?php endif; ?>href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($row['link']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
              <?php endif; ?>
              <?php if ($row['storageRetrievalRequestLink'] ?? false): ?>
                <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($row['storageRetrievalRequestLink']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
              <?php endif; ?>
              <?php if ($row['ILLRequestLink'] ?? false): ?>
                <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($row['ILLRequestLink']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
              <?php endif; ?>
            <?php else: ?>
              <?php /* Begin Unavailable Items (Recalls) 
                       Note that $row['status'] contains raw status from ILS */ ?>
              <span class="text-danger"><?=$this->transEsc("Available by Request")?><link property="availability" href="http://schema.org/OutOfStock" /></span>
              <?php if ($row['returnDate'] ?? false): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><?php endif; ?>
              <?php if ($row['duedate'] ?? false): ?>
                &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
              <?php endif; ?>
              <?php if (($row['requests_placed'] ?? 0) > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <?php endif; ?>
              <?php if ($row['link'] ?? false): ?>
                <a class="<?=$check ? 'checkRequest' : ''?> placehold" <?php if (!empty($row['linkLightbox'])): ?>data-lightbox <?php endif; ?>href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($row['link']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
              <?php endif; ?>
              <?=$this->relais()->renderButtonIfActive($this->driver ?? null)?>
            <?php endif; ?>
          <?php endif; ?>
          <?php /* Embed item structured data: library, barcode, call number */ ?>
          <?php if ($row['barcode'] ?? false): ?>
            <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($row['barcode'])?>" />
          <?php endif; ?>
          <?php if ($row['callnumber'] ?? false): ?>
            <meta property="sku" content="<?=$this->escapeHtmlAttr($row['callnumber'])?>" />
          <?php endif; ?>
          <?php /* Declare that the item is to be borrowed, not for sale */ ?>
          <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
          <link property="itemOffered" href="#record" />
        </td>
      </tr>
      <?php endforeach; ?>
      </table>
    <?php endif; ?>
  <?php endforeach; ?>

<?php endif; ?>

<?php
// Show message for special case when we don't have holdings data to show, but
// may still have holdings at CRL.
// Removed until collection holdings are better finalized in FOLIO.
// if (!$this->driver->isOnline() && (empty($holdings['holdings']) || $total_items === 0)): ?>

<?php // endif; ?>

<?php if (!empty($holdings['total']) && $paginator = $this->tab->getPaginator($holdings['total'], $holdings['page'], $holdings['itemLimit'])): ?>
  <?=$this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml', ['page' => $holdings['page']])?>
<?php endif; ?>
<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
  <h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
  <table class="table table-striped">
    <?php foreach ($history as $row): ?>
      <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
