<footer class="hidden-print">
  <div class="container">
    <div class="footer-container">
      <div class="footer-column">
        <?php $this->slot('footer-left')->start(); ?>
        <h2><?=$this->transEsc('Search Options')?></h2>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
        </ul>
        <?=$this->slot('footer-left')->end(); ?>
      </div>
      <div class="footer-column">
        <?php $this->slot('footer-center')->start(); ?>
        <h2><?=$this->transEsc('Find More')?></h2>
        <ul>
          <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
          <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
          <li><a href="<?=$this->url('channels-home')?>"><?=$this->transEsc('channel_explore')?></a></li>
          <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
          <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
          <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('Interlibrary Loan Requests')?></a></li>
        </ul>
        <?=$this->slot('footer-center')->end(); ?>
      </div>
      <div class="footer-column">
        <?php $this->slot('footer-right')->start(); ?>
        <h2><?=$this->transEsc('Need Help?')?></h2>
        <ul>
          <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'asklibrary']) ?>"><?=$this->transEsc('Ask a Librarian')?></a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'faq']) ?>"><?=$this->transEsc('FAQs')?></a></li>
        </ul>
        <?=$this->slot('footer-right')->end(); ?>
      </div>
      <div class="footer-column">
        <div class="footer-social">
          <p><strong>Follow CRL</strong></p>
            <ul>
              <li class="social-link">
                <a href="https://www.facebook.com/CenterforResearchLibraries"><i class="fa fa-facebook"></i></a>
              </li>
              <li class="social-link">
                <a href="https://twitter.com/CRL_global"><i class="fa fa-twitter"></i></a>
              </li>
              <li class="social-link">
                <a href="https://instagram.com/crllibrary"><i class="fa fa-instagram"></i></a>
              </li>
              <li class="social-link">
                <a href="https://www.youtube.com/crldotedu"><i class="fa fa-youtube"></i></a>
              </li>
              <li class="social-link">
                <a href="https://www.crl.edu/connect"><i class="fa fa-envelope"></i></a>
              </li>
              <li class="social-link">
                <a href="https://www.crl.edu/news/feed"><i class="fa fa-rss"></i></a>
              </li>
            </ul>
            <br>
            <p><a href="/connect">Sign up for the Connect Newsletter</a></p>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-box footer-bottom container" style="height: 74px;">
    <div id="boxes-box-crl_footer_bottom" class="boxes-box">
      <div class="boxes-box-content">
        <ul>
          <li><a href="http://catalog.crl.edu">catalog.crl.edu</a></li>
          <li><a href="http://ddsnext.crl.edu">ddsnext.crl.edu</a></li>
          <li><a href="http://icon.crl.edu">icon.crl.edu</a></li>
          <li><a href="http://papr.crl.edu">papr.crl.edu</a></li>
          <li><a href="http://edesiderata.crl.edu">edesiderata.crl.edu</a></li>
          <li><a href="http://liblicense.crl.edu">liblicense.crl.edu</a></li>
          <li><a href="http://gcollections.crl.edu">gcollections.crl.edu</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
