<footer class="hidden-print">
  <div class="container">
    <div class="footer-container">
      <div class="footer-column">
        <?php $this->slot('footer-left')->start(); ?>
        <h2><?=$this->transEsc('Search Options')?></h2>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
          <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
        </ul>
        <?=$this->slot('footer-left')->end(); ?>
      </div>
      <div class="footer-column">
        <?php $this->slot('footer-right')->start(); ?>
        <h2><?=$this->transEsc('Need Help?')?></h2>
        <ul>
          <li><a href="<?=$this->url('content-page', ['page' => 'borrowing']) ?>"><?=$this->transEsc('Interlibrary Loan Requests')?></a></li>
          <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
        </ul>
        <?=$this->slot('footer-right')->end(); ?>
      </div>
      <div class="footer-column">
        <div class="footer-social">
          <p><strong>Follow CRL</strong></p>
            <ul>
              <li class="social-link">
                <a href="https://www.facebook.com/CenterforResearchLibraries"><i class="fa fa-facebook"></i></a>
              </li>
              <li class="social-link">
                <a href="https://twitter.com/CRL_global"><i class="fa fa-twitter"></i></a>
              </li>
              <li class="social-link">
                <a href="https://instagram.com/crllibrary"><i class="fa fa-instagram"></i></a>
              </li>
              <li class="social-link">
                <a href="https://www.youtube.com/crldotedu"><i class="fa fa-youtube"></i></a>
              </li>
              <li class="social-link">
                <a href="https://www.crl.edu/connect"><i class="fa fa-envelope"></i></a>
              </li>
              <li class="social-link">
                <a href="https://www.crl.edu/news/feed"><i class="fa fa-rss"></i></a>
              </li>
            </ul>
            <p><a href="https://www.crl.edu/connect">Sign up for the Connect Newsletter</a></p>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-box footer-bottom container" style="height: 74px;">
    <div id="boxes-box-crl_footer_bottom" class="boxes-box">
      <div class="boxes-box-content">
        <ul>
          <li><a href="https://www.crl.edu/accessibility-statement">Accessibility Statement</a></li>
          <li><a href="https://www.crl.edu/privacy-policy">Privacy Policy</a></li>
          <li>Powered by <a href="https://vufind.org/vufind/">VuFind</a> and <a href="https://www.folio.org/">FOLIO</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
