<?php $this->headTitle($this->translate('Borrowing from CRL')); ?>

<h1><?=$this->transEsc('Borrowing from CRL') ?></h1>

<p>Scholars and researchers from CRL member institutions have free and unlimited use of the CRL collections through Interlibrary loan.</p>
<br /><br />

<div class="block" id="Illiad_div">
	<!--2016-10-17 new section per AW-->
	<h4>Request CRL Items from your library</h4>
	<p>
		Via Member ILL form:
		<select name="CRL_member_ILL_form_link_list" id="CRL_member_ILL_form_link_list" class="CRL_member_ILL_form_link_list"></select>
		<button id="Illiad_arrow" alt="Open ILL form for the chosen CRL member" type="button" name="button">Go</button>
	</p>
	<div class="boxfoot">
		<a class="more" href="http://www.crl.edu/services/borrowing/" target="_blank">All other methods »</a>
	</div>
</div>
