<div class="crl-borrowing">
  <?php $this->headTitle($this->translate('Borrowing from CRL')); ?>

    <h1><?=$this->transEsc('Borrowing from CRL') ?></h1>

    <p>
      Scholars and researchers from CRL member libraries have access to CRL collections without charge through interlibrary loan, <a href="http://ddsnext.crl.edu/" data-lightbox-ignore="">digitized CRL collections</a> or by appointment in our <a href="https://www.crl.edu/services/reading-room" data-lightbox-ignore="">reading room</a>. Non-members have limited access to the collection for a fee. Loan periods are unlimited, but materials are subject to recall if another CRL institution requests the materials. Global Member libraries have full access to digitized CRL collections, and microforms. Libraries outside the CRL library community may <a href="https://www.crl.edu/services/borrowing/non-member-lending" data-lightbox-ignore="">borrow</a> on behalf of researchers for a prepaid fee, subject to certain limitations. <a href="https://www.crl.edu/services/lending" data-lightbox-ignore="">Learn more about CRL lending</a>.
    </p>

  	<div id="Illiad_div">
  		<strong>Request Items from Your Member Library</strong>
  		<p>
  			Via Member ILL form:
  			<select name="CRL_member_ILL_form_link_list" id="CRL_member_ILL_form_link_list" class="CRL_member_ILL_form_link_list" style="max-width: 100%;"></select>
  			<button id="Illiad_arrow" alt="Open ILL form for the chosen CRL member" type="button" name="button">Go</button>
  		</p>
  		<div class="boxfoot">

  		</div>
  	</div>

  <?php
  // If this content is being loaded in a lightbox we need to trigger the
  // list building JS inline. Unfortunatly inline JS may be needed here as it does
  // not look like there is an event triggered when lightox is opened.
  $script = <<<JS
    $(document).ready(fill_CRL_member_ILL_form_link_list());
  JS;
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
  ?>

</div>
